services:
  api:
    build:
      context: ../
      dockerfile: ./Dockerfile
      target: development
    pull_policy: build
    environment:
      NODE_ENV: development
      DB_SYNCHRONIZE: ${DB_SYNCHRONIZE:-true}
    ports:
      - ${API_PORT:-3000}:${PORT:-3000}
    volumes:
      - api-data:/app/uploads
      - api-sqlite-data:/app/data
      - ../src:/app/src
