services:
  postgres:
    ports:
      - ${DB_PORT:-5432}:5432

  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-dev@hexabot.ai}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-dev_only}
      PGADMIN_CONFIG_SERVER_MODE: ${PGADMIN_CONFIG_SERVER_MODE:-False}
    depends_on:
      - postgres
    ports:
      - ${PGADMIN_PORT:-9000}:80
    networks:
      - db-network
