import { ConversationalWorkflowContext, createAction } from '@hexabot-ai/api';
import { z } from 'zod';

// Keep custom action files under src/extensions/actions and name them *.action.ts.
// Hexabot loads the compiled dist/extensions/actions/**/*.action.js files at startup.

// Input fields are values the workflow author maps into the action step.
const dummyActionInputSchema = z.object({
  name: z.string().min(1).default('Hexabot').meta({
    title: 'Name',
    description: 'Name to include in the generated greeting.',
  }),
});
// Output fields become available to later workflow steps.
const dummyActionOutputSchema = z.object({
  text: z.string().meta({
    title: 'Text',
    description: 'Greeting generated by the dummy action.',
  }),
  generatedAt: z.iso.datetime().meta({
    title: 'Generated at',
    description: 'ISO date when the dummy action executed.',
  }),
});
// Settings are configured on the action step and are separate from runtime input.
const dummyActionSettingsSchema = z.object({
  greeting: z.string().min(1).default('Hello').meta({
    title: 'Greeting',
    description: 'Greeting prefix used by the dummy action.',
  }),
});

type DummyActionInput = z.infer<typeof dummyActionInputSchema>;
type DummyActionOutput = z.infer<typeof dummyActionOutputSchema>;
type DummyActionSettings = z.infer<typeof dummyActionSettingsSchema>;

const DummyAction = createAction<
  DummyActionInput,
  DummyActionOutput,
  ConversationalWorkflowContext,
  DummyActionSettings
>({
  // Action names must be snake_case and unique across built-in/custom actions.
  name: 'dummy_echo',
  description: 'Example custom action that returns a configurable greeting.',
  inputSchema: dummyActionInputSchema,
  outputSchema: dummyActionOutputSchema,
  settingsSchema: dummyActionSettingsSchema,
  icon: 'FlaskConical',
  color: '#2563EB',
  group: 'examples',

  // Hexabot validates input/settings before execute() and validates the returned output.
  execute({ input, settings }) {
    // Write what magic your action should be doing here.
    return {
      text: `${settings.greeting}, ${input.name}!`,
      generatedAt: new Date().toISOString(),
    };
  },
});

export default DummyAction;
